### ISSUE TITLE
Is there a fast way to delete all records? And Python3

### ISSUE THREAD

**Issue by dkupper76** [ciscocms/cdr-receiver-db#1]
Hello,

First, I want to thank you for creating this repository and all the work that you put into it, along with your giving back to the community.  I am a huge opensource advocate.  I am fairly new to programming, especially Python, as I am brand new to Python, Javascript is the first language I learned. I am an Engineer that works with  Collaboration, Unified Communications, Security, and Network Products from Cisco, Microsoft, and other vendors.  

I was trying to do some quick validation testing with this repository for a design that I am working on, when I got hit with a nasty surprise, Toll Fraud Attempts getting through my Expressway and putting 2000 entries in these CDRs in a 10 min period.  These attempts are fruitless for those trying because there is not PSTN connected to this Lab setup, and I usually just block their IP addresses and block the patterns either in the Expressway or the Firewall.  But now with the 2000 entries, I am only able to delete 20 at a time.  Is there a way to delete all the entries at once?  

Also, Like I said, I am very new to Python and don't know a whole lot about it yet, but I noticed it is written in Python 2.7, do you know if this will work in Python 3?  Are there any plans to update it to Python 3?  When I get in a better position if it is not updated to Python 3, hopefully I will be able to give back to the community and re-create this in Python 3, but if someone beats me too it, that would be awesome.  

If you have any answers to any of these questions will you please let me know?

Thank you,

Daryl

**Comment by ryanquinlan** [comment]
Hi Daryl,

Thank you for the kind words. It's always nice to see something you've built get used by someone else.

The simplest way to nuke your records is to just delete the `records.db` file that gets created when you first launch. It will be in the root of the repo. If you check out `models.py` you'll see that each time the app loads it's designed to rebuild the tables in the db. If the db/table already exists we skip that step.

The interface is using Flask-Admin, could be a good exercise to extend the interface to include a delete all function.

As for Python 3, I just did a quick check and it runs fine using the versions captured in requirements.txt for dependencies on Python 3.8.3.

**Comment by dkupper76** [comment]
Hi Ryan,

I greatly appreciate your quick reply and your help.  That sounds much simpler to delete the records.db instead of manually deleting 20 records at a time with over 2000 records in the db. Usually, whenever I get slammed with the toll fraud attempts like that, I block them and it doesn't happen again for a few weeks, the attempts are annoying, but at-least they cannot successfully commit toll fraud against this lab system. 

That is great news that this will work in python 3, I will test it on a different Linux server that only has Python 3 and PIP 3 installed.  I was just a little short on time as I am working a complex Cisco to Microsoft Design/Integration, and the customer wanted to know if the CDRs from CMS would show the SfB/Lync Participants in a scheduled Skype for Business Meeting aka Dual-Homed Conference.  Not only am I working with the CMS design, but also looking at a few different options for call reporting and analytics, and while I am working with a very good Product from a Solutions Plus Partner, I am also trying to use this to grow my skills such as Python, the Elasticstack aka ELK Stack, the TIG Stack, and even containers and Kubernetes, etc. but the timeline has shortened so I needed something quick to provide answers.

Awesome idea to extend the Flask-Admin interface to include a delete all function, I am looking forward to diving into this deeper and trying out some of the other repositories here. While I am far from an expert in Javascript, I have gotten pretty comfortable with it in working with the XAPI in the CE Endpoints and a couple of chatbots, I am still very new to Python, and I am finding it a good exercise to not only read, watch videos, but also look at other people's code, and contribute where I can or at-least use it for hands on experience in learning.  

I might be rambling on a bit, but I don't know if many know how valuable and how appreciated repositories like these are that can be applied to real world instances and used on the job, instead of just a "Hello World" that you might get in a College class on introduction to programming etc.

Thank you,

Daryl
